export type DireccionEvento = 'Enviado' | 'Recibido'
export type EstadoContrato = 'PROPOSED' | 'RECEIVED' | 'AGREED' | 'CORE_PENDING' | 'CONFIRMED'

export type ModuloIntegracion = {
  id: string
  nombre: string
  descripcion: string
}

export type EventoIntegracion = {
  nombre: string
  direccion: DireccionEvento
  modulos: string[]
  gatillo: string
  descripcion: string
  payload: string[]
  estadoContrato: EstadoContrato
  nota?: string
}

export const modulosIntegracion: ModuloIntegracion[] = [
  {
    id: 'M1',
    nombre: 'Ciudadanos y Expedientes',
    descripcion: 'Resoluciones administrativas e informacion del ciclo de vida de obras.',
  },
  {
    id: 'M2',
    nombre: 'Atencion Ciudadana',
    descripcion: 'Reclamos de infraestructura y actualizaciones de ordenes originadas por reclamos.',
  },
  {
    id: 'M6',
    nombre: 'Ambiente y Servicios Urbanos',
    descripcion: 'Alertas de riesgos urbanos, reparaciones solicitadas y resultados operativos.',
  },
  {
    id: 'M7',
    nombre: 'Transito',
    descripcion: 'Incidentes viales y autorizaciones o rechazos de cortes de calle.',
  },
  {
    id: 'M9',
    nombre: 'Core Municipal',
    descripcion: 'Convenciones tecnicas comunes y catalogo de eventos publicados y consumidos.',
  },
]

export const eventosIntegracion: EventoIntegracion[] = [
  {
    nombre: 'complaintRouted',
    direccion: 'Recibido',
    modulos: ['M2'],
    gatillo: 'Atencion Ciudadana clasifica un reclamo como problema de infraestructura.',
    descripcion: 'Registra una solicitud de intervencion disponible para evaluacion por Obras Publicas.',
    payload: ['ticketId', 'category', 'subcategory', 'description', 'location', 'priority', 'createdAt', 'evidence', 'affectedPeople'],
    estadoContrato: 'PROPOSED',
    nota: 'El identificador definitivo del ticket debe acordarse con M2.',
  },
  {
    nombre: 'complaintEscalated',
    direccion: 'Recibido',
    modulos: ['M2'],
    gatillo: 'Atencion Ciudadana aumenta la prioridad de un reclamo previamente derivado.',
    descripcion: 'Actualiza la prioridad de la solicitud u orden relacionada y genera alerta operativa.',
    payload: ['ticketId', 'previousPriority', 'newPriority', 'reason', 'escalatedAt'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'infrastructureRepairRequested',
    direccion: 'Recibido',
    modulos: ['M6'],
    gatillo: 'Ambiente informa un dano de infraestructura cuya resolucion corresponde a Obras Publicas.',
    descripcion: 'Permite evaluar la solicitud y crear una orden de trabajo relacionada.',
    payload: ['requestId', 'damageType', 'severity', 'location', 'detectedIn', 'complaintId', 'publicSafetyRisk', 'requestedAt'],
    estadoContrato: 'RECEIVED',
    nota: 'Para este origen, workOrderCompleted.sourceRequestId conserva requestId.',
  },
  {
    nombre: 'containerDamaged',
    direccion: 'Recibido',
    modulos: ['M6'],
    gatillo: 'Ambiente detecta un contenedor danado que podria requerir intervencion de Obras.',
    descripcion: 'Se procesa solamente cuando requiresPublicWorks es true.',
    payload: ['containerId', 'containerCode', 'zoneId', 'location', 'damageType', 'severity', 'requiresPublicWorks', 'detectedAt', 'complaintId'],
    estadoContrato: 'RECEIVED',
    nota: 'No se asume que containerId sea automaticamente sourceRequestId.',
  },
  {
    nombre: 'treeRiskDetected',
    direccion: 'Recibido',
    modulos: ['M6'],
    gatillo: 'Ambiente detecta riesgo de arbolado con impacto en via publica.',
    descripcion: 'Obras evalua la intervencion cuando requiresPublicWorks es true; HIGH y CRITICAL tienen prioridad.',
    payload: ['treeId', 'surveyCode', 'species', 'zoneId', 'location', 'riskLevel', 'riskType', 'healthStatus', 'suggestedIntervention', 'requiresStreetClosure', 'requiresPublicWorks', 'surveyedAt'],
    estadoContrato: 'RECEIVED',
    nota: 'Se consume treeRiskDetected en lugar de urbanRiskDetected.',
  },
  {
    nombre: 'trafficIncidentRegistered',
    direccion: 'Recibido',
    modulos: ['M7'],
    gatillo: 'Transito registra un incidente vial con posible dano de infraestructura.',
    descripcion: 'Obras registra el incidente y evalua si debe generar una intervencion.',
    payload: ['incidentId', 'occurredAt', 'location', 'description', 'reportedDamage', 'severity', 'evidence'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'streetClosureAuthorized',
    direccion: 'Recibido',
    modulos: ['M7'],
    gatillo: 'Transito autoriza una solicitud de corte realizada por Obras Publicas.',
    descripcion: 'Actualiza el corte a Autorizada y permite programar dentro del periodo autorizado.',
    payload: ['closureRequestId', 'publicWorksProjectId', 'workOrderId', 'authorizedSections', 'authorizedFrom', 'authorizedTo', 'conditions', 'notes', 'authorizedBy'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'streetClosureRejected',
    direccion: 'Recibido',
    modulos: ['M7'],
    gatillo: 'Transito rechaza una solicitud de corte de calle.',
    descripcion: 'La orden debe reprogramarse, modificar el periodo solicitado o quedar bloqueada.',
    payload: ['closureRequestId', 'publicWorksProjectId', 'workOrderId', 'reason', 'rejectedAt', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'caseFileResolved',
    direccion: 'Recibido',
    modulos: ['M1'],
    gatillo: 'Expedientes emite una resolucion administrativa relacionada con una obra.',
    descripcion: 'Registra la resolucion dentro del historial administrativo de la obra.',
    payload: ['caseFileId', 'publicWorksProjectId', 'resolutionType', 'result', 'resolvedAt', 'notes', 'documentation'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'publicWorksProjectCreated',
    direccion: 'Enviado',
    modulos: ['M1'],
    gatillo: 'Se registra un nuevo proyecto y queda en estado Borrador.',
    descripcion: 'Informa la creacion administrativa inicial de la obra.',
    payload: ['publicWorksProjectId', 'name', 'description', 'scope', 'location', 'estimatedBudget', 'estimatedDuration', 'technicalManager', 'status', 'createdAt'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'publicWorksProjectSubmittedForApproval',
    direccion: 'Enviado',
    modulos: ['M1'],
    gatillo: 'La obra pasa de Borrador a Pendiente de aprobacion.',
    descripcion: 'Informa que la obra quedo lista para evaluacion formal.',
    payload: ['publicWorksProjectId', 'submittedAt', 'submittedBudget', 'submittedDeadline', 'technicalManager', 'submittedBy', 'documentation', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'publicWorksProjectApproved',
    direccion: 'Enviado',
    modulos: ['M1'],
    gatillo: 'La obra pasa al estado Aprobada.',
    descripcion: 'Notifica aprobacion tecnica y financiera del proyecto.',
    payload: ['publicWorksProjectId', 'approvedBudget', 'approvedDeadline', 'approvedAt', 'approvedBy', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'publicWorksProjectRejected',
    direccion: 'Enviado',
    modulos: ['M1'],
    gatillo: 'La obra pasa al estado Rechazada.',
    descripcion: 'Registra decision, motivo y documentacion observada.',
    payload: ['publicWorksProjectId', 'rejectedAt', 'reason', 'notes', 'rejectedBy', 'observedDocumentation'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'publicWorksProjectStarted',
    direccion: 'Enviado',
    modulos: ['M1'],
    gatillo: 'Comienza formalmente la ejecucion de una obra aprobada.',
    descripcion: 'Informa fecha real de inicio, plan vigente y responsable.',
    payload: ['publicWorksProjectId', 'actualStartDate', 'startedBy', 'currentPlan', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'publicWorksProgressRegistered',
    direccion: 'Enviado',
    modulos: ['M1'],
    gatillo: 'Se registra un avance fisico o presupuestario.',
    descripcion: 'Comunica progreso asociado a etapa o hito sin modificar el estado general.',
    payload: ['publicWorksProjectId', 'stageId', 'milestoneId', 'physicalProgressPercentage', 'executedAmount', 'registeredAt', 'registeredBy', 'notes', 'documentation'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'publicWorksExtensionRequested',
    direccion: 'Enviado',
    modulos: ['M1'],
    gatillo: 'Se solicita ampliar plazo, presupuesto o ambos.',
    descripcion: 'Registra solicitud justificada de ampliacion en el historial de obra.',
    payload: ['extensionId', 'publicWorksProjectId', 'extensionType', 'currentValue', 'requestedValue', 'reason', 'justification', 'documentation', 'requestedAt', 'requestedBy'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'publicWorksExtensionApproved',
    direccion: 'Enviado',
    modulos: ['M1'],
    gatillo: 'Una solicitud de ampliacion es aprobada.',
    descripcion: 'Informa valores anteriores y aprobados de la ampliacion.',
    payload: ['extensionId', 'publicWorksProjectId', 'extensionType', 'previousValue', 'approvedValue', 'approvedAt', 'approvedBy', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'publicWorksExtensionRejected',
    direccion: 'Enviado',
    modulos: ['M1'],
    gatillo: 'Una solicitud de ampliacion es rechazada.',
    descripcion: 'Informa motivo, usuario y fecha de rechazo.',
    payload: ['extensionId', 'publicWorksProjectId', 'extensionType', 'requestedValue', 'reason', 'rejectedAt', 'rejectedBy', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'publicWorksProjectSuspended',
    direccion: 'Enviado',
    modulos: ['M1'],
    gatillo: 'La ejecucion de una obra es suspendida.',
    descripcion: 'Comunica motivo, impacto estimado y ordenes afectadas.',
    payload: ['publicWorksProjectId', 'suspendedAt', 'reason', 'estimatedImpact', 'affectedWorkOrders', 'suspendedBy', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'publicWorksProjectResumed',
    direccion: 'Enviado',
    modulos: ['M1'],
    gatillo: 'Una obra suspendida vuelve al estado En ejecucion.',
    descripcion: 'Informa reanudacion, nueva planificacion y ordenes habilitadas.',
    payload: ['publicWorksProjectId', 'resumedAt', 'reason', 'resumedBy', 'updatedPlan', 'enabledWorkOrders', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'publicWorksProjectCompleted',
    direccion: 'Enviado',
    modulos: ['M1'],
    gatillo: 'La obra pasa al estado Finalizada.',
    descripcion: 'Informa cierre definitivo, costo final, certificaciones y documentacion final.',
    payload: ['publicWorksProjectId', 'actualCompletionDate', 'finalCost', 'result', 'completionPercentage', 'certifications', 'finalDocumentation', 'completedBy'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'workOrderCreated',
    direccion: 'Enviado',
    modulos: ['M2', 'M6', 'M7'],
    gatillo: 'Se registra una nueva orden de trabajo.',
    descripcion: 'Comunica la creacion a quien haya originado la solicitud.',
    payload: ['workOrderId', 'publicWorksProjectId', 'sourceRequestId', 'interventionType', 'description', 'location', 'priority', 'status', 'createdAt'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'workOrderScheduled',
    direccion: 'Enviado',
    modulos: ['M2', 'M6', 'M7'],
    gatillo: 'Se establece fecha y horario previstos para realizar la orden.',
    descripcion: 'Avisa al modulo origen cuando se ejecutara la reparacion.',
    payload: ['workOrderId', 'sourceRequestId', 'scheduledFrom', 'scheduledTo', 'estimatedDuration', 'location', 'plannedResources', 'status', 'scheduledBy'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'workOrderAssigned',
    direccion: 'Enviado',
    modulos: ['M2', 'M6', 'M7'],
    gatillo: 'Una orden recibe una cuadrilla responsable.',
    descripcion: 'Informa cuadrilla, maquinaria y materiales planificados.',
    payload: ['workOrderId', 'sourceRequestId', 'crewId', 'scheduledDate', 'assignedMachinery', 'plannedMaterials', 'status', 'assignedBy'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'workOrderStarted',
    direccion: 'Enviado',
    modulos: ['M2', 'M6', 'M7'],
    gatillo: 'La cuadrilla comienza la ejecucion de la orden.',
    descripcion: 'Comunica inicio operativo y conserva sourceRequestId.',
    payload: ['workOrderId', 'sourceRequestId', 'startedAt', 'crewId', 'startedBy', 'status', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'workOrderPaused',
    direccion: 'Enviado',
    modulos: ['M2', 'M6', 'M7'],
    gatillo: 'Una orden se detiene temporalmente.',
    descripcion: 'Informa pausa, motivo, progreso y observaciones.',
    payload: ['workOrderId', 'sourceRequestId', 'pausedAt', 'reason', 'pausedBy', 'currentProgress', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'workOrderDelayed',
    direccion: 'Enviado',
    modulos: ['M2', 'M6', 'M7'],
    gatillo: 'Una orden no puede cumplir la fecha prevista.',
    descripcion: 'Informa demora y fecha estimada nueva.',
    payload: ['workOrderId', 'sourceRequestId', 'reason', 'originalScheduledDate', 'estimatedNewDate', 'reportedBy', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'workOrderRescheduled',
    direccion: 'Enviado',
    modulos: ['M2', 'M6', 'M7'],
    gatillo: 'Se modifica la fecha u horario previsto para ejecutar una orden.',
    descripcion: 'Comunica reprogramacion al modulo que origino la solicitud.',
    payload: ['workOrderId', 'sourceRequestId', 'previousScheduledDate', 'newScheduledDate', 'reason', 'rescheduledBy', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'workOrderCompleted',
    direccion: 'Enviado',
    modulos: ['M2', 'M6', 'M7'],
    gatillo: 'La cuadrilla informa que termino el trabajo y cargo evidencia requerida.',
    descripcion: 'Representa finalizacion operativa, no siempre validacion definitiva.',
    payload: ['workOrderId', 'sourceRequestId', 'publicWorksProjectId', 'result', 'completedAt', 'consumedMaterials', 'notes', 'evidence', 'crewId'],
    estadoContrato: 'PROPOSED',
    nota: 'M6 solicito payload minimo workOrderId, sourceRequestId, completedAt, outcome y attachments[].',
  },
  {
    nombre: 'workOrderValidated',
    direccion: 'Enviado',
    modulos: ['M2', 'M6', 'M7'],
    gatillo: 'Un inspector confirma que la intervencion fue correctamente ejecutada.',
    descripcion: 'Representa la conclusion satisfactoria cuando el proceso externo requiere confirmacion definitiva.',
    payload: ['workOrderId', 'sourceRequestId', 'validatedAt', 'validationResult', 'inspectorId', 'notes', 'evidence'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'workOrderReopened',
    direccion: 'Enviado',
    modulos: ['M2', 'M6', 'M7'],
    gatillo: 'Una orden terminada no supera la validacion y debe volver a ejecutarse.',
    descripcion: 'Mantiene relacion con el proceso original y registra correcciones requeridas.',
    payload: ['workOrderId', 'sourceRequestId', 'reopenedAt', 'reason', 'inspectorId', 'requiredCorrections', 'priority', 'notes'],
    estadoContrato: 'PROPOSED',
  },
  {
    nombre: 'streetClosureRequested',
    direccion: 'Enviado',
    modulos: ['M7'],
    gatillo: 'Una obra u orden requiere interrumpir total o parcialmente el transito.',
    descripcion: 'Solicita autorizacion formal al modulo de Transito.',
    payload: ['closureRequestId', 'publicWorksProjectId', 'workOrderId', 'reason', 'affectedSections', 'requestedFrom', 'requestedTo', 'closureType', 'estimatedDuration', 'requestedBy', 'notes'],
    estadoContrato: 'PROPOSED',
  },
]
